[build]
  command = "npm run build:prod"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "20"
  NODE_ENV = "production"
  NETLIFY = "true"
  NODE_OPTIONS = "--max-old-space-size=4096"

[functions]
  node_bundler = "esbuild"
  directory = "netlify/functions"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-XSS-Protection = "1; mode=block"

# Cache static assets
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache images
[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"

# Handle registration with Netlify function
[[redirects]]
  from = "/api/auth/register"
  to = "/.netlify/functions/register"
  status = 200

# Handle NextAuth.js pages (keep these as they're for UI pages, not API routes)
[[redirects]]
  from = "/api/auth/signin"
  to = "/login"
  status = 302

[[redirects]]
  from = "/api/auth/signout"
  to = "/login"
  status = 302

[[redirects]]
  from = "/api/auth/error"
  to = "/login"
  status = 302