[build]
  command = "npm run build:prod"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "20"
  NODE_ENV = "production"

# Handle Next.js routing properly - let Next.js handle routing
# Remove the SPA redirect rule as it conflicts with Next.js SSR

[functions]
  node_bundler = "esbuild"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-XSS-Protection = "1; mode=block" 