[build]
  command = "npm run build:prod"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "20"
  NODE_ENV = "production"
  NETLIFY = "true"

[functions]
  node_bundler = "esbuild"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-XSS-Protection = "1; mode=block"

# Cache static assets
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache images
[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"

# Critical: Handle NextAuth.js API routes properly
[[redirects]]
  from = "/api/auth/*"
  to = "/.netlify/functions/___netlify-handler"
  status = 200
  force = true

# Handle NextAuth.js callback URLs
[[redirects]]
  from = "/api/auth/callback/*"
  to = "/.netlify/functions/___netlify-handler"
  status = 200
  force = true

# Handle all other API routes
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/___netlify-handler"
  status = 200
  force = true

# Handle NextAuth.js pages
[[redirects]]
  from = "/api/auth/signin"
  to = "/login"
  status = 302

[[redirects]]
  from = "/api/auth/signout"
  to = "/login"
  status = 302

[[redirects]]
  from = "/api/auth/error"
  to = "/login"
  status = 302